[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"
